organise:
  - "all"
  - "best"
  - "classical"
  - "dance"
  - "feel"
  - "funny ol' life"
  - "pas_understando"
  - "random"
  - "school"
  - "smile"
  - "trippin"
  # This is temp hold.
  # Songs that have been reviewed but don't make it into any other playlist.
  # Hence, "un"classified.
  - "un"

ignore:
  - "Episodes for Later"
  - "sets"
  - "TODO"
  - "yt nailed it"
